### ISSUE TITLE
Git tag for 0.1.0 missing?

### ISSUE THREAD

**Issue by hartwork** [qingyunha/ppty#2]
Hi @qingyunha,

I noticed there is no Git tag for https://pypi.org/project/ppty/0.1.0/ . Is commit 8ba993333a3dc69ca33aa10a99406db6e600c1b9 identical with the release? Did you forget to push the tag?

Best, Sebastian

**Comment by hartwork** [comment]
Any thoughts?

**Comment by qingyunha** [comment]
Done.  https://github.com/qingyunha/ppty/tree/0.1.0

**Comment by hartwork** [comment]
@qingyunha thank you! :+1:
